spring.application.name=shelfkeeper
jwt.secret=${JWT_SECRET}
jwt.expiration-ms=3600000

spring.datasource.url=${DB_AK_APP}
spring.datasource.username=${DB_USER}
spring.datasource.password=${DB_PASS}
spring.datasource.driver-class-name=org.postgresql.Driver