CREATE FUNCTION set_updated_at()
RETURNS TRIGGER AS $$
BEGIN
  NEW.updated_at = CURRENT_TIMESTAMP;
  RETURN NEW;
END;
$$ LANGUAGE plpgsql;

CREATE TABLE authors (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name VARCHAR(255) NOT NULL,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT authors_name_key UNIQUE (name)
);

CREATE TABLE books (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  title VARCHAR(255) NOT NULL,
  author_id INTEGER NOT NULL,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT books_author_id_fkey FOREIGN KEY (author_id) REFERENCES authors (id)
);

CREATE TABLE users (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name VARCHAR(255) NOT NULL,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE admin_users (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name VARCHAR(255) NOT NULL,
  mail VARCHAR(255) NOT NULL,
  pass VARCHAR(255) NOT NULL,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT admin_users_mail_key UNIQUE (mail)
);

CREATE TABLE loan_records (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id INTEGER NOT NULL,
  book_id INTEGER NOT NULL,
  loan_date DATE NOT NULL,
  due_date DATE NOT NULL,
  return_date DATE,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT loan_records_user_id_fkey FOREIGN KEY (user_id) REFERENCES users (id),
  CONSTRAINT loan_records_book_id_fkey FOREIGN KEY (book_id) REFERENCES books (id),
  CONSTRAINT loan_records_due_date_check CHECK (due_date >= loan_date),
  CONSTRAINT loan_records_return_date_check CHECK (return_date IS NULL OR return_date >= loan_date)
);

CREATE INDEX books_author_id_idx ON books (author_id);
CREATE INDEX books_title_idx ON books (title);
CREATE INDEX loan_records_user_id_idx ON loan_records (user_id);
CREATE INDEX loan_records_book_id_idx ON loan_records (book_id);

CREATE UNIQUE INDEX loan_records_open_book_id_idx
  ON loan_records (book_id)
  WHERE return_date IS NULL;

CREATE TRIGGER authors_set_updated_at
  BEFORE UPDATE ON authors
  FOR EACH ROW
  EXECUTE FUNCTION set_updated_at();

CREATE TRIGGER books_set_updated_at
  BEFORE UPDATE ON books
  FOR EACH ROW
  EXECUTE FUNCTION set_updated_at();

CREATE TRIGGER users_set_updated_at
  BEFORE UPDATE ON users
  FOR EACH ROW
  EXECUTE FUNCTION set_updated_at();

CREATE TRIGGER admin_users_set_updated_at
  BEFORE UPDATE ON admin_users
  FOR EACH ROW
  EXECUTE FUNCTION set_updated_at();

CREATE TRIGGER loan_records_set_updated_at
  BEFORE UPDATE ON loan_records
  FOR EACH ROW
  EXECUTE FUNCTION set_updated_at();
